### ISSUE TITLE
get 55  errors

### ISSUE THREAD

**Issue by metalost** [TheNoobCompany/TheNoobBot#11]
im using VS 2017 how to resolve it?

![okkk](https://user-images.githubusercontent.com/31975628/55814139-fa864b00-5abb-11e9-8fd0-3e158ea29547.jpg)

**Comment by metalost** [comment]
I tried to compile the pandawow branch that you can see in the "branches" section of the code.

**Comment by TheNoobCompany** [comment]
First compile RecastLayer project alone. I think you're missing some old redistribuable.

There is a known issue with VS 2017 if you installed it on a fresh window, it may have deactivated some Visual Studio redistribuable, you need to reinstall them properly.
https://developercommunity.visualstudio.com/content/problem/332815/visual-c-redistributable-2017-install-removes-visu.html

**Comment by metalost** [comment]
Try to compile in batches (only recast layer), this time, with a clean installation of VS 2019 and the latest version of windows 10

![image](https://user-images.githubusercontent.com/31975628/56090532-41d05b00-5e71-11e9-8d65-b0e489999f59.png)
![image](https://user-images.githubusercontent.com/31975628/56090545-76dcad80-5e71-11e9-8f63-0882fc148d1f.png)

Thank you so much for reading and sharing your work, it's great

**Comment by TheNoobCompany** [comment]
No, not like that, right click on RecastLayer on in the solution explorer to compile it alone...

**Comment by metalost** [comment]
![image](https://user-images.githubusercontent.com/31975628/56109758-f3c66080-5f1f-11e9-84e5-871b54fcb499.png)
1>------ Operación Compilar iniciada: proyecto: RecastLayer, configuración: Release Win32 ------
1>LINK : fatal error LNK1104: no se puede abrir el archivo 'MSCOREE.lib'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(719,5): error MSB6006: "link.exe" salió con el código 1104.
1>Compilación del proyecto "RecastLayer.vcxproj" terminada -- ERROR.
========== Compilar: 0 correctos, 1 incorrectos, 0 actualizados, 0 omitidos ==========


-------------------------

this is what came out when I tried to compile only the recast layer by the solutions explorer

Thank you very much for your attention!

**Comment by TheNoobCompany** [comment]
https://social.msdn.microsoft.com/Forums/es-ES/7cc02d97-3eb4-4a30-a0d9-bbce309eeb60/error-al-compilar-1gtlink-fatal-error-lnk1104-no-se-puede-abrir-el-archivo-cprogramobj?forum=vsgenerales

**Comment by metalost** [comment]
![image](https://user-images.githubusercontent.com/31975628/56115054-8838bf00-5f30-11e9-8c7a-43726b50eb02.png)

Basically there they come to the conclusion that the error is due to the fact that they were not specific in the introduction of the address and besides that, they should have used quotation marks ( " ) but I see that in the code that is fine

Thank you very much for reading

**Comment by metalost** [comment]
![image](https://user-images.githubusercontent.com/31975628/56115575-ad79fd00-5f31-11e9-9a81-8e67fdc5b36d.png)

I see that I managed to solve one of the problems by clicking as shown in the image

However I see that the Mscoree.lib still persists, excuse my little knowledge about c++ how could I solve that?

**Comment by TheNoobCompany** [comment]
Try googling those errors, and installing all pre-requisites you may need

**Comment by metalost** [comment]
Well, I managed to compile the code, installing the net 4.5 and the created 4.6.1 SDK, everything has gone great regarding the compilation, that releases an exe in the folder TheNoobBot but ... does nothing

Thanks for reading! I leave you image

![image](https://user-images.githubusercontent.com/31975628/56403008-9ab34100-622d-11e9-801f-7518d8af9074.png)

**Comment by TheNoobCompany** [comment]
The server is obviously down, you will have to bypass the login check if you want to go further.

Also, you will probably need to update offsets etc. The bot is not usable per say at the moment !

**Comment by TheNoobCompany** [comment]
Good luck for your adventure !
